/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/atc/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_applications"];
    put?: never;
    post: operations["create_application"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/applications/review-sheet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_review_sheet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/applications/sheet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_application_sheet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/applications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_application"];
    put: operations["update_application"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/applications/{id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["review_application"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/controllers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_controllers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_training"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_active"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_training_applications"];
    put?: never;
    post: operations["create_training_application"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/applications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_training_application"];
    put: operations["update_training_application"];
    post?: never;
    delete: operations["delete_application"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/applications/{id}/response": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["respond_to_application"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/applications/{id}/responses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_responses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/by-user/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_by_user"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/finished": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_finished"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/record-sheet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_record_sheet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_training"];
    put: operations["update_training"];
    post?: never;
    delete: operations["delete_training"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/atc/trainings/{id}/record": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["set_record_sheet"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compat/euroscope/metar/metar.php": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_metar_by_query"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compat/euroscope/metar/{icao}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_metar_by_path"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compat/online-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["online_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compat/trackaudio/mandatory_version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["trackaudio_version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compat/vplaaf/areas.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["vplaaf_areas"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_events"];
    put?: never;
    post: operations["create_event"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/past": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_past_events"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/airspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_airspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/controllers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_positions"];
    put?: never;
    post: operations["create_position"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/controllers/{position_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_position"];
    post?: never;
    delete: operations["delete_position"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/controllers/{position_id}/booking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["book_position"];
    post?: never;
    delete: operations["cancel_position_booking"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/slots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_slots"];
    put?: never;
    post: operations["create_slot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/slots/bookings.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["export_bookings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/slots/{slot_id}/booking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["put_booking"];
    post?: never;
    delete: operations["delete_event_slot_booking"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_event"];
    put: operations["update_event"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["active_flights"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/by-callsign/{callsign}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["flight_by_callsign"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/by-callsign/{callsign}/route": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["route_by_callsign"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/by-callsign/{callsign}/warnings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["warnings_by_callsign"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/mine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["my_flight"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flights/temporary/by-plan/warnings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["temporary_warnings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/navdata/preferred-routes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_preferred_routes"];
    put?: never;
    post: operations["create_preferred_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/navdata/preferred-routes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_preferred_route"];
    put: operations["update_preferred_route"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sectors/current/permission": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["current_permission"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_current"];
    put?: never;
    post?: never;
    delete: operations["logout"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sheets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_sheets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sheets/{sheetId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_sheet"];
    put: operations["upsert_sheet"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["upload_image"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_users"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/atc/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_my_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{id}/atc/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_status"];
    put: operations["set_status"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{id}/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["set_roles"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/__unsafe_assume_user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["unsafe_assume_user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/device_authorization": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["device_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccessTokenRequest: {
      client_id?: string;
      client_secret?: string;
      code?: string;
      code_verifier?: string;
      device_code?: string;
      grant_type?: string;
      refresh_token?: string;
    };
    AtcApplicationDto: {
      application_filing_answers: components["schemas"]["SheetFieldAnswerDto"][];
      /** Format: date-time */
      applied_at: string;
      id: string;
      review_filing_answers?: components["schemas"]["SheetFieldAnswerDto"][] | null;
      status: components["schemas"]["AtcApplicationStatus"];
      user: components["schemas"]["UserDto"];
      user_id: string;
    };
    AtcApplicationRequest: {
      request_answers: components["schemas"]["SheetRequestField"][];
    };
    AtcApplicationReviewRequest: {
      review_answers: components["schemas"]["SheetRequestField"][];
      status: components["schemas"]["AtcApplicationStatus"];
    };
    /** @enum {string} */
    AtcApplicationStatus: "submitted" | "in-waitlist" | "approved" | "rejected" | "aborted";
    AtcApplicationSummaryDto: {
      /** Format: date-time */
      applied_at: string;
      id: string;
      status: components["schemas"]["AtcApplicationStatus"];
      user: components["schemas"]["UserDto"];
      user_email?: string | null;
      user_id: string;
    };
    AtcPermissionDto: {
      position_kind_id: string;
      /** Format: date-time */
      solo_expires_at?: string | null;
      state: components["schemas"]["UserControllerState"];
    };
    AtcPermissionRequest: {
      position_kind_id: string;
      /** Format: date-time */
      solo_expires_at?: string | null;
      state: components["schemas"]["UserControllerState"];
    };
    AtcStatusDto: {
      is_absent: boolean;
      is_visiting: boolean;
      permissions: components["schemas"]["AtcPermissionDto"][];
      rating: string;
      user: components["schemas"]["UserDto"];
      user_id: string;
    };
    AtcStatusRequest: {
      is_absent: boolean;
      is_visiting: boolean;
      permissions: components["schemas"]["AtcPermissionRequest"][];
      rating: string;
    };
    AuthApiErrorBody: {
      error: components["schemas"]["OAuthErrorCode"];
      error_description: string;
    };
    CompatControllerDto: {
      callsign: string;
      /** Format: int32 */
      cid: number;
      frequency: string;
      name: string;
    };
    CompatFutureControllerDto: {
      callsign: string;
      end: string;
      /** Format: date-time */
      end_utc: string;
      name: string;
      start: string;
      /** Format: date-time */
      start_utc: string;
    };
    CompatPilotDto: {
      aircraft?: string | null;
      arrival?: string | null;
      callsign: string;
      /** Format: int32 */
      cid: number;
      departure?: string | null;
      name: string;
    };
    CompatVatprcStatusDto: {
      controllers: components["schemas"]["CompatControllerDto"][];
      future_controllers: components["schemas"]["CompatFutureControllerDto"][];
      /** Format: date-time */
      last_updated: string;
      pilots: components["schemas"]["CompatPilotDto"][];
    };
    DeviceAuthorizationRequest: {
      client_id: string;
      scope?: string | null;
    };
    DeviceAuthorizationResponse: {
      device_code: string;
      /** Format: int32 */
      expires_in: number;
      /** Format: int32 */
      interval?: number | null;
      user_code: string;
      verification_uri: string;
      verification_uri_complete?: string | null;
    };
    EventAirspaceDto: {
      /** Format: date-time */
      created_at: string;
      description: string;
      event_id: string;
      icao_codes: string[];
      id: string;
      name: string;
      /** Format: date-time */
      updated_at: string;
    };
    EventAirspaceSaveRequest: {
      description: string;
      icao_codes: string[];
      name: string;
    };
    EventAtcPositionBookRequest: {
      user_id?: string | null;
    };
    EventAtcPositionBookingDto: {
      /** Format: date-time */
      booked_at: string;
      user: components["schemas"]["UserDto"];
      user_id: string;
    };
    EventAtcPositionDto: {
      booking?: null | components["schemas"]["EventAtcPositionBookingDto"];
      callsign: string;
      /** Format: date-time */
      end_at: string;
      event: components["schemas"]["EventDto"];
      id: string;
      minimum_controller_state: components["schemas"]["UserControllerState"];
      position_kind_id: string;
      remarks?: string | null;
      /** Format: date-time */
      start_at: string;
    };
    EventAtcPositionSaveRequest: {
      callsign: string;
      /** Format: date-time */
      end_at: string;
      minimum_controller_state: components["schemas"]["UserControllerState"];
      position_kind_id: string;
      remarks?: string | null;
      /** Format: date-time */
      start_at: string;
    };
    EventBookingDto: {
      /** Format: date-time */
      created_at: string;
      id: string;
      /** Format: date-time */
      updated_at: string;
      user?: null | components["schemas"]["UserDto"];
      user_id: string;
    };
    EventDto: {
      community_link?: string | null;
      /** Format: date-time */
      created_at: string;
      description: string;
      /** Format: date-time */
      end_at: string;
      /** Format: date-time */
      end_booking_at?: string | null;
      id: string;
      image_url?: string | null;
      /** Format: date-time */
      start_at: string;
      /** Format: date-time */
      start_atc_booking_at?: string | null;
      /** Format: date-time */
      start_booking_at?: string | null;
      title: string;
      title_en?: string | null;
      /** Format: date-time */
      updated_at: string;
      vatsim_link?: string | null;
    };
    EventSaveRequest: {
      community_link?: string | null;
      description: string;
      /** Format: date-time */
      end_at: string;
      /** Format: date-time */
      end_booking_at?: string | null;
      image_url?: string | null;
      /** Format: date-time */
      start_at: string;
      /** Format: date-time */
      start_atc_booking_at?: string | null;
      /** Format: date-time */
      start_booking_at?: string | null;
      title: string;
      title_en?: string | null;
      vatsim_link?: string | null;
    };
    EventSlotBookingRequest: {
      user_id?: string | null;
    };
    EventSlotDto: {
      aircraft_type_icao?: string | null;
      airspace: components["schemas"]["EventAirspaceDto"];
      airspace_id: string;
      booking?: null | components["schemas"]["EventBookingDto"];
      callsign?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      enter_at: string;
      event_id: string;
      id: string;
      /** Format: date-time */
      leave_at?: string | null;
      /** Format: date-time */
      updated_at: string;
    };
    EventSlotSaveRequest: {
      aircraft_type_icao?: string | null;
      airspace_id: string;
      callsign?: string | null;
      /** Format: date-time */
      enter_at: string;
      /** Format: date-time */
      leave_at?: string | null;
    };
    FlightDto: {
      aircraft: string;
      /** Format: int64 */
      altitude: number;
      arrival: string;
      callsign: string;
      cid: string;
      /** Format: int64 */
      cruising_level: number;
      departure: string;
      equipment: string;
      id: string;
      /** Format: date-time */
      last_observed_at: string;
      navigation_performance: string;
      raw_route: string;
      transponder: string;
    };
    FlightFix: {
      identifier: string;
    };
    FlightLeg: {
      from: components["schemas"]["FlightFix"];
      leg_identifier: string;
      to: components["schemas"]["FlightFix"];
    };
    HealthResponse: {
      database: string;
      status: string;
    };
    /** @enum {string} */
    LevelRestrictionType:
      | "standard-even"
      | "standard-odd"
      | "standard"
      | "flight-level-even"
      | "flight-level-odd"
      | "flight-level";
    /** @enum {string} */
    OAuthErrorCode:
      | "invalid_request"
      | "invalid_client"
      | "invalid_grant"
      | "invalid_scope"
      | "unauthorized_client"
      | "unsupported_grant_type"
      | "authorization_pending"
      | "expired_token";
    PreferredRouteDto: {
      allowed_altitudes: number[];
      arrival: string;
      cruising_level_restriction: components["schemas"]["LevelRestrictionType"];
      departure: string;
      id: string;
      /** Format: int32 */
      minimal_altitude: number;
      raw_route: string;
      remarks: string;
      /** Format: date-time */
      valid_from?: string | null;
      /** Format: date-time */
      valid_until?: string | null;
    };
    PreferredRouteSaveRequest: {
      allowed_altitudes?: number[];
      arrival: string;
      cruising_level_restriction: components["schemas"]["LevelRestrictionType"];
      departure: string;
      /** Format: int32 */
      minimal_altitude: number;
      raw_route: string;
      remarks: string;
      /** Format: date-time */
      valid_from?: string | null;
      /** Format: date-time */
      valid_until?: string | null;
    };
    ProblemDetails: {
      detail: string;
      /** Format: int32 */
      status: number;
      title: string;
      type: string;
    };
    SectorPermissionResponse: {
      has_permission: boolean;
      sector_type: string;
    };
    SheetDto: {
      fields: components["schemas"]["SheetFieldDto"][];
      id: string;
      name: string;
    };
    SheetFieldAnswerDto: {
      answer: string;
      field: components["schemas"]["SheetFieldDto"];
    };
    SheetFieldDto: {
      description_en?: string | null;
      description_zh?: string | null;
      id: string;
      is_deleted: boolean;
      kind: components["schemas"]["SheetFieldKind"];
      name_en?: string | null;
      name_zh: string;
      /** Format: uint32 */
      sequence: number;
      sheet_id: string;
      single_choice_options: string[];
    };
    /** @enum {string} */
    SheetFieldKind: "short-text" | "long-text" | "single-choice";
    SheetFieldSaveRequest: {
      description_en?: string | null;
      description_zh?: string | null;
      id: string;
      kind: components["schemas"]["SheetFieldKind"];
      name_en?: string | null;
      name_zh: string;
      /** Format: uint32 */
      sequence: number;
      single_choice_options: string[];
    };
    SheetRequestField: {
      answer: string;
      id: string;
    };
    SheetSaveRequest: {
      fields: components["schemas"]["SheetFieldSaveRequest"][];
      name: string;
    };
    TokenDto: {
      /** Format: date-time */
      expires_at: string;
      /** Format: date-time */
      issued_at: string;
      user: components["schemas"]["UserDto"];
    };
    TokenResponse: {
      access_token: string;
      /** Format: int32 */
      expires_in: number;
      refresh_token?: string | null;
      scope: string;
      token_type: string;
    };
    TrainingApplicationCreateRequest: {
      name: string;
      slots: components["schemas"]["TrainingApplicationCreateRequestSlot"][];
    };
    TrainingApplicationCreateRequestSlot: {
      /** Format: date-time */
      end_at: string;
      /** Format: date-time */
      start_at: string;
    };
    TrainingApplicationDto: {
      /** Format: date-time */
      created_at: string;
      id: string;
      name: string;
      slots: components["schemas"]["TrainingApplicationSlotDto"][];
      status: components["schemas"]["TrainingApplicationStatus"];
      train_id?: string | null;
      trainee: components["schemas"]["UserDto"];
      trainee_email?: string | null;
      trainee_id: string;
      /** Format: date-time */
      updated_at: string;
    };
    TrainingApplicationResponseDto: {
      application_id: string;
      comment: string;
      /** Format: date-time */
      created_at: string;
      id: string;
      is_accepted: boolean;
      trainer: components["schemas"]["UserDto"];
      trainer_id: string;
      /** Format: date-time */
      updated_at: string;
    };
    TrainingApplicationResponseRequest: {
      comment: string;
      slot_id?: string | null;
    };
    TrainingApplicationSlotDto: {
      application_id: string;
      /** Format: date-time */
      end_at: string;
      id: string;
      /** Format: date-time */
      start_at: string;
    };
    /** @enum {string} */
    TrainingApplicationStatus: "pending" | "accepted" | "rejected" | "cancelled";
    TrainingDto: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      deleted_at?: string | null;
      /** Format: date-time */
      end_at: string;
      id: string;
      name: string;
      record_sheet_filing?: components["schemas"]["SheetFieldAnswerDto"][] | null;
      record_sheet_filing_id?: string | null;
      /** Format: date-time */
      start_at: string;
      trainee: components["schemas"]["UserDto"];
      trainee_id: string;
      trainer: components["schemas"]["UserDto"];
      trainer_id: string;
      /** Format: date-time */
      updated_at: string;
    };
    TrainingRecordRequest: {
      request_answers: components["schemas"]["SheetRequestField"][];
    };
    TrainingSaveRequest: {
      /** Format: date-time */
      end_at: string;
      name: string;
      /** Format: date-time */
      start_at: string;
      trainee_id: string;
      trainer_id: string;
    };
    UnsafeAssumeUserRequest: {
      cid: string;
      email?: string | null;
      full_name?: string | null;
      id?: string | null;
      roles?: string[] | null;
    };
    UploadImageResponse: {
      url: string;
    };
    /** @enum {string} */
    UserControllerState: "student" | "under-mentor" | "solo" | "certified" | "mentor";
    UserDto: {
      cid: string;
      /** Format: date-time */
      created_at: string;
      direct_roles: components["schemas"]["UserRole"][];
      full_name: string;
      id: string;
      moodle_account?: null | components["schemas"]["UserMoodleInfoDto"];
      roles: components["schemas"]["UserRole"][];
      /** Format: date-time */
      updated_at: string;
    };
    UserMoodleInfoDto: {
      id: string;
    };
    /** @enum {string} */
    UserRole:
      | "staff"
      | "volunteer"
      | "division-director"
      | "controller-training-director"
      | "controller-training-director-assistant"
      | "controller-training-instructor"
      | "controller-training-mentor"
      | "controller-training-sop-editor"
      | "community-director"
      | "operation-director"
      | "operation-director-assistant"
      | "operation-sector-editor"
      | "operation-loa-editor"
      | "event-director"
      | "lead-event-coordinator"
      | "event-coordinator"
      | "event-graphics-designer"
      | "tech-director"
      | "tech-director-assistant"
      | "tech-afv-facility-engineer"
      | "controller"
      | "api-client"
      | "user";
    WarningMessage: {
      field: components["schemas"]["WarningMessageField"];
      field_index?: number | null;
      message_code: components["schemas"]["WarningMessageCode"];
      parameter?: string | null;
    };
    /** @enum {string} */
    WarningMessageCode:
      | "no-rvsm"
      | "no-rnav1"
      | "rnp-ar"
      | "rnp-ar-without-rf"
      | "no-transponder"
      | "route-direct-segment"
      | "route-leg-direction"
      | "airway-require-approval"
      | "not-preferred-route"
      | "cruising-level-mismatch"
      | "cruising-level-not-allowed"
      | "cruising-level-too-low"
      | "route-match-preferred";
    /** @enum {string} */
    WarningMessageField: "equipment" | "transponder" | "navigation-performance" | "route" | "cruising-level";
  };
  responses: {
    /** @description Internal server error */
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_applications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcApplicationSummaryDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_application: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtcApplicationRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcApplicationSummaryDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_review_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_application_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtcApplicationRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  review_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtcApplicationReviewRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_controllers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcStatusDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_training: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_active: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_training_applications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_training_application: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingApplicationCreateRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_training_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_training_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingApplicationCreateRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  delete_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  respond_to_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingApplicationResponseRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationResponseDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_responses: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training application ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingApplicationResponseDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_by_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ULID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_finished: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_record_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_training: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_training: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  delete_training: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  set_record_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Training ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrainingRecordRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_metar_by_query: {
    parameters: {
      query?: {
        /** @description ICAO code */
        icao?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_metar_by_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ICAO code */
        icao: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  online_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompatVatprcStatusDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  trackaudio_version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  vplaaf_areas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_events: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_event: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_past_events: {
    parameters: {
      query?: {
        /** @description Latest event start time to include */
        until?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_airspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventAirspaceSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAirspaceDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_positions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAtcPositionDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_position: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventAtcPositionSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAtcPositionDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_position: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Position ULID */
        position_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventAtcPositionSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAtcPositionDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  delete_position: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Position ULID */
        position_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  book_position: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Position ULID */
        position_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventAtcPositionBookRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAtcPositionBookingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  cancel_position_booking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Position ULID */
        position_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventAtcPositionBookingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_slots: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventSlotDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_slot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventSlotSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventSlotDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  export_bookings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV export of slot bookings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": unknown;
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  put_booking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Slot ULID */
        slot_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventSlotBookingRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventBookingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  delete_event_slot_booking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        event_id: string;
        /** @description Slot ULID */
        slot_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventBookingDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_event: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_event: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Event ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  active_flights: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlightDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  flight_by_callsign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Callsign */
        callsign: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlightDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  route_by_callsign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Callsign */
        callsign: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlightLeg"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  warnings_by_callsign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Callsign */
        callsign: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WarningMessage"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  my_flight: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlightDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  temporary_warnings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WarningMessage"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_preferred_routes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredRouteDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  create_preferred_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreferredRouteSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredRouteDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_preferred_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Preferred route ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredRouteDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  update_preferred_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Preferred route ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreferredRouteSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredRouteDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  current_permission: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SectorPermissionResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_sheets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Sheet ID */
        sheetId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  upsert_sheet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Sheet ID */
        sheetId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SheetSaveRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SheetDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  upload_image: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadImageResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  list_users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_my_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcStatusDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  get_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcStatusDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  set_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtcStatusRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtcStatusDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  set_roles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ULID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  unsafe_assume_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnsafeAssumeUserRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description OAuth error response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
      /** @description OAuth client authentication error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
    };
  };
  authorize: {
    parameters: {
      query: {
        /** @description OAuth response type. Must be code. */
        response_type: string;
        /** @description OAuth client identifier */
        client_id: string;
        /** @description Client redirect URI */
        redirect_uri: string;
        /** @description Opaque client state */
        state?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirects to authorization destination */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  device_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["DeviceAuthorizationRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceAuthorizationResponse"];
        };
      };
      /** @description OAuth error response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
      /** @description OAuth client authentication error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
    };
  };
  token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["AccessTokenRequest"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description OAuth error response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
      /** @description OAuth client authentication error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthApiErrorBody"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
}
