/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as FlightsIndexRouteImport } from './routes/flights/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ControllersIndexRouteImport } from './routes/controllers/index'
import { Route as UsersMeRouteImport } from './routes/users/me'
import { Route as NavdataPreferredRoutesRouteImport } from './routes/navdata/preferred-routes'
import { Route as FlightsCallsignRouteImport } from './routes/flights/$callsign'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ControllersTrainingsIndexRouteImport } from './routes/controllers/trainings/index'
import { Route as ControllersApplicationsIndexRouteImport } from './routes/controllers/applications/index'
import { Route as DocsUtilsImageRouteImport } from './routes/docs/utils/image'
import { Route as ControllersTrainingsIdRouteImport } from './routes/controllers/trainings/$id'
import { Route as ControllersApplicationsNewRouteImport } from './routes/controllers/applications/new'
import { Route as ControllersApplicationsIdRouteImport } from './routes/controllers/applications/$id'
import { Route as DocPilotTs3RouteImport } from './routes/_doc/pilot/ts3'
import { Route as DocPilotStartToFlyRouteImport } from './routes/_doc/pilot/start-to-fly'
import { Route as DocPilotPilotSoftwaresRouteImport } from './routes/_doc/pilot/pilot-softwares'
import { Route as DocPilotIntroductionToFlyRouteImport } from './routes/_doc/pilot/introduction-to-fly'
import { Route as DocDivisionStaffRouteImport } from './routes/_doc/division/staff'
import { Route as DocDivisionPrivacyRouteImport } from './routes/_doc/division/privacy'
import { Route as DocDivisionMeetingRouteImport } from './routes/_doc/division/meeting'
import { Route as DocDivisionIntroductionRouteImport } from './routes/_doc/division/introduction'
import { Route as DocDivisionApiRouteImport } from './routes/_doc/division/api'
import { Route as DocControllerVisitingAndTransferringRouteImport } from './routes/_doc/controller/visiting-and-transferring'
import { Route as DocControllerSectorRouteImport } from './routes/_doc/controller/sector'
import { Route as DocControllerLoaRouteImport } from './routes/_doc/controller/loa'
import { Route as DocControllerControllerRegulationsRouteImport } from './routes/_doc/controller/controller-regulations'
import { Route as DocControllerControllerListRouteImport } from './routes/_doc/controller/controller-list'
import { Route as DocControllerBecomeAControllerRouteImport } from './routes/_doc/controller/become-a-controller'
import { Route as DocAirspaceVfrRouteImport } from './routes/_doc/airspace/vfr'
import { Route as DocAirspaceStationRouteImport } from './routes/_doc/airspace/station'
import { Route as DocAirspaceSopRouteImport } from './routes/_doc/airspace/sop'
import { Route as DocAirspaceRvsmRouteImport } from './routes/_doc/airspace/rvsm'
import { Route as DocAirspaceFirRouteImport } from './routes/_doc/airspace/fir'

const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlightsRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const ControllersIndexRoute = ControllersIndexRouteImport.update({
  id: '/controllers/',
  path: '/controllers/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeRoute = UsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NavdataPreferredRoutesRoute = NavdataPreferredRoutesRouteImport.update({
  id: '/navdata/preferred-routes',
  path: '/navdata/preferred-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsCallsignRoute = FlightsCallsignRouteImport.update({
  id: '/$callsign',
  path: '/$callsign',
  getParentRoute: () => FlightsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllersTrainingsIndexRoute =
  ControllersTrainingsIndexRouteImport.update({
    id: '/controllers/trainings/',
    path: '/controllers/trainings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControllersApplicationsIndexRoute =
  ControllersApplicationsIndexRouteImport.update({
    id: '/controllers/applications/',
    path: '/controllers/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsUtilsImageRoute = DocsUtilsImageRouteImport.update({
  id: '/docs/utils/image',
  path: '/docs/utils/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllersTrainingsIdRoute = ControllersTrainingsIdRouteImport.update({
  id: '/controllers/trainings/$id',
  path: '/controllers/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllersApplicationsNewRoute =
  ControllersApplicationsNewRouteImport.update({
    id: '/controllers/applications/new',
    path: '/controllers/applications/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControllersApplicationsIdRoute =
  ControllersApplicationsIdRouteImport.update({
    id: '/controllers/applications/$id',
    path: '/controllers/applications/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocPilotTs3Route = DocPilotTs3RouteImport.update({
  id: '/_doc/pilot/ts3',
  path: '/pilot/ts3',
  getParentRoute: () => rootRouteImport,
} as any)
const DocPilotStartToFlyRoute = DocPilotStartToFlyRouteImport.update({
  id: '/_doc/pilot/start-to-fly',
  path: '/pilot/start-to-fly',
  getParentRoute: () => rootRouteImport,
} as any)
const DocPilotPilotSoftwaresRoute = DocPilotPilotSoftwaresRouteImport.update({
  id: '/_doc/pilot/pilot-softwares',
  path: '/pilot/pilot-softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const DocPilotIntroductionToFlyRoute =
  DocPilotIntroductionToFlyRouteImport.update({
    id: '/_doc/pilot/introduction-to-fly',
    path: '/pilot/introduction-to-fly',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocDivisionStaffRoute = DocDivisionStaffRouteImport.update({
  id: '/_doc/division/staff',
  path: '/division/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDivisionPrivacyRoute = DocDivisionPrivacyRouteImport.update({
  id: '/_doc/division/privacy',
  path: '/division/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDivisionMeetingRoute = DocDivisionMeetingRouteImport.update({
  id: '/_doc/division/meeting',
  path: '/division/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDivisionIntroductionRoute = DocDivisionIntroductionRouteImport.update({
  id: '/_doc/division/introduction',
  path: '/division/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDivisionApiRoute = DocDivisionApiRouteImport.update({
  id: '/_doc/division/api',
  path: '/division/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocControllerVisitingAndTransferringRoute =
  DocControllerVisitingAndTransferringRouteImport.update({
    id: '/_doc/controller/visiting-and-transferring',
    path: '/controller/visiting-and-transferring',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocControllerSectorRoute = DocControllerSectorRouteImport.update({
  id: '/_doc/controller/sector',
  path: '/controller/sector',
  getParentRoute: () => rootRouteImport,
} as any)
const DocControllerLoaRoute = DocControllerLoaRouteImport.update({
  id: '/_doc/controller/loa',
  path: '/controller/loa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocControllerControllerRegulationsRoute =
  DocControllerControllerRegulationsRouteImport.update({
    id: '/_doc/controller/controller-regulations',
    path: '/controller/controller-regulations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocControllerControllerListRoute =
  DocControllerControllerListRouteImport.update({
    id: '/_doc/controller/controller-list',
    path: '/controller/controller-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocControllerBecomeAControllerRoute =
  DocControllerBecomeAControllerRouteImport.update({
    id: '/_doc/controller/become-a-controller',
    path: '/controller/become-a-controller',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocAirspaceVfrRoute = DocAirspaceVfrRouteImport.update({
  id: '/_doc/airspace/vfr',
  path: '/airspace/vfr',
  getParentRoute: () => rootRouteImport,
} as any)
const DocAirspaceStationRoute = DocAirspaceStationRouteImport.update({
  id: '/_doc/airspace/station',
  path: '/airspace/station',
  getParentRoute: () => rootRouteImport,
} as any)
const DocAirspaceSopRoute = DocAirspaceSopRouteImport.update({
  id: '/_doc/airspace/sop',
  path: '/airspace/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const DocAirspaceRvsmRoute = DocAirspaceRvsmRouteImport.update({
  id: '/_doc/airspace/rvsm',
  path: '/airspace/rvsm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocAirspaceFirRoute = DocAirspaceFirRouteImport.update({
  id: '/_doc/airspace/fir',
  path: '/airspace/fir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/flights': typeof FlightsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/flights/$callsign': typeof FlightsCallsignRoute
  '/navdata/preferred-routes': typeof NavdataPreferredRoutesRoute
  '/users/me': typeof UsersMeRoute
  '/controllers': typeof ControllersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/users': typeof UsersIndexRoute
  '/airspace/fir': typeof DocAirspaceFirRoute
  '/airspace/rvsm': typeof DocAirspaceRvsmRoute
  '/airspace/sop': typeof DocAirspaceSopRoute
  '/airspace/station': typeof DocAirspaceStationRoute
  '/airspace/vfr': typeof DocAirspaceVfrRoute
  '/controller/become-a-controller': typeof DocControllerBecomeAControllerRoute
  '/controller/controller-list': typeof DocControllerControllerListRoute
  '/controller/controller-regulations': typeof DocControllerControllerRegulationsRoute
  '/controller/loa': typeof DocControllerLoaRoute
  '/controller/sector': typeof DocControllerSectorRoute
  '/controller/visiting-and-transferring': typeof DocControllerVisitingAndTransferringRoute
  '/division/api': typeof DocDivisionApiRoute
  '/division/introduction': typeof DocDivisionIntroductionRoute
  '/division/meeting': typeof DocDivisionMeetingRoute
  '/division/privacy': typeof DocDivisionPrivacyRoute
  '/division/staff': typeof DocDivisionStaffRoute
  '/pilot/introduction-to-fly': typeof DocPilotIntroductionToFlyRoute
  '/pilot/pilot-softwares': typeof DocPilotPilotSoftwaresRoute
  '/pilot/start-to-fly': typeof DocPilotStartToFlyRoute
  '/pilot/ts3': typeof DocPilotTs3Route
  '/controllers/applications/$id': typeof ControllersApplicationsIdRoute
  '/controllers/applications/new': typeof ControllersApplicationsNewRoute
  '/controllers/trainings/$id': typeof ControllersTrainingsIdRoute
  '/docs/utils/image': typeof DocsUtilsImageRoute
  '/controllers/applications': typeof ControllersApplicationsIndexRoute
  '/controllers/trainings': typeof ControllersTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/flights/$callsign': typeof FlightsCallsignRoute
  '/navdata/preferred-routes': typeof NavdataPreferredRoutesRoute
  '/users/me': typeof UsersMeRoute
  '/controllers': typeof ControllersIndexRoute
  '/events': typeof EventsIndexRoute
  '/flights': typeof FlightsIndexRoute
  '/users': typeof UsersIndexRoute
  '/airspace/fir': typeof DocAirspaceFirRoute
  '/airspace/rvsm': typeof DocAirspaceRvsmRoute
  '/airspace/sop': typeof DocAirspaceSopRoute
  '/airspace/station': typeof DocAirspaceStationRoute
  '/airspace/vfr': typeof DocAirspaceVfrRoute
  '/controller/become-a-controller': typeof DocControllerBecomeAControllerRoute
  '/controller/controller-list': typeof DocControllerControllerListRoute
  '/controller/controller-regulations': typeof DocControllerControllerRegulationsRoute
  '/controller/loa': typeof DocControllerLoaRoute
  '/controller/sector': typeof DocControllerSectorRoute
  '/controller/visiting-and-transferring': typeof DocControllerVisitingAndTransferringRoute
  '/division/api': typeof DocDivisionApiRoute
  '/division/introduction': typeof DocDivisionIntroductionRoute
  '/division/meeting': typeof DocDivisionMeetingRoute
  '/division/privacy': typeof DocDivisionPrivacyRoute
  '/division/staff': typeof DocDivisionStaffRoute
  '/pilot/introduction-to-fly': typeof DocPilotIntroductionToFlyRoute
  '/pilot/pilot-softwares': typeof DocPilotPilotSoftwaresRoute
  '/pilot/start-to-fly': typeof DocPilotStartToFlyRoute
  '/pilot/ts3': typeof DocPilotTs3Route
  '/controllers/applications/$id': typeof ControllersApplicationsIdRoute
  '/controllers/applications/new': typeof ControllersApplicationsNewRoute
  '/controllers/trainings/$id': typeof ControllersTrainingsIdRoute
  '/docs/utils/image': typeof DocsUtilsImageRoute
  '/controllers/applications': typeof ControllersApplicationsIndexRoute
  '/controllers/trainings': typeof ControllersTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/flights': typeof FlightsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/flights/$callsign': typeof FlightsCallsignRoute
  '/navdata/preferred-routes': typeof NavdataPreferredRoutesRoute
  '/users/me': typeof UsersMeRoute
  '/controllers/': typeof ControllersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_doc/airspace/fir': typeof DocAirspaceFirRoute
  '/_doc/airspace/rvsm': typeof DocAirspaceRvsmRoute
  '/_doc/airspace/sop': typeof DocAirspaceSopRoute
  '/_doc/airspace/station': typeof DocAirspaceStationRoute
  '/_doc/airspace/vfr': typeof DocAirspaceVfrRoute
  '/_doc/controller/become-a-controller': typeof DocControllerBecomeAControllerRoute
  '/_doc/controller/controller-list': typeof DocControllerControllerListRoute
  '/_doc/controller/controller-regulations': typeof DocControllerControllerRegulationsRoute
  '/_doc/controller/loa': typeof DocControllerLoaRoute
  '/_doc/controller/sector': typeof DocControllerSectorRoute
  '/_doc/controller/visiting-and-transferring': typeof DocControllerVisitingAndTransferringRoute
  '/_doc/division/api': typeof DocDivisionApiRoute
  '/_doc/division/introduction': typeof DocDivisionIntroductionRoute
  '/_doc/division/meeting': typeof DocDivisionMeetingRoute
  '/_doc/division/privacy': typeof DocDivisionPrivacyRoute
  '/_doc/division/staff': typeof DocDivisionStaffRoute
  '/_doc/pilot/introduction-to-fly': typeof DocPilotIntroductionToFlyRoute
  '/_doc/pilot/pilot-softwares': typeof DocPilotPilotSoftwaresRoute
  '/_doc/pilot/start-to-fly': typeof DocPilotStartToFlyRoute
  '/_doc/pilot/ts3': typeof DocPilotTs3Route
  '/controllers/applications/$id': typeof ControllersApplicationsIdRoute
  '/controllers/applications/new': typeof ControllersApplicationsNewRoute
  '/controllers/trainings/$id': typeof ControllersTrainingsIdRoute
  '/docs/utils/image': typeof DocsUtilsImageRoute
  '/controllers/applications/': typeof ControllersApplicationsIndexRoute
  '/controllers/trainings/': typeof ControllersTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/flights'
    | '/auth/callback'
    | '/docs/$'
    | '/events/$id'
    | '/flights/$callsign'
    | '/navdata/preferred-routes'
    | '/users/me'
    | '/controllers'
    | '/events/'
    | '/flights/'
    | '/users'
    | '/airspace/fir'
    | '/airspace/rvsm'
    | '/airspace/sop'
    | '/airspace/station'
    | '/airspace/vfr'
    | '/controller/become-a-controller'
    | '/controller/controller-list'
    | '/controller/controller-regulations'
    | '/controller/loa'
    | '/controller/sector'
    | '/controller/visiting-and-transferring'
    | '/division/api'
    | '/division/introduction'
    | '/division/meeting'
    | '/division/privacy'
    | '/division/staff'
    | '/pilot/introduction-to-fly'
    | '/pilot/pilot-softwares'
    | '/pilot/start-to-fly'
    | '/pilot/ts3'
    | '/controllers/applications/$id'
    | '/controllers/applications/new'
    | '/controllers/trainings/$id'
    | '/docs/utils/image'
    | '/controllers/applications'
    | '/controllers/trainings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/docs/$'
    | '/events/$id'
    | '/flights/$callsign'
    | '/navdata/preferred-routes'
    | '/users/me'
    | '/controllers'
    | '/events'
    | '/flights'
    | '/users'
    | '/airspace/fir'
    | '/airspace/rvsm'
    | '/airspace/sop'
    | '/airspace/station'
    | '/airspace/vfr'
    | '/controller/become-a-controller'
    | '/controller/controller-list'
    | '/controller/controller-regulations'
    | '/controller/loa'
    | '/controller/sector'
    | '/controller/visiting-and-transferring'
    | '/division/api'
    | '/division/introduction'
    | '/division/meeting'
    | '/division/privacy'
    | '/division/staff'
    | '/pilot/introduction-to-fly'
    | '/pilot/pilot-softwares'
    | '/pilot/start-to-fly'
    | '/pilot/ts3'
    | '/controllers/applications/$id'
    | '/controllers/applications/new'
    | '/controllers/trainings/$id'
    | '/docs/utils/image'
    | '/controllers/applications'
    | '/controllers/trainings'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/flights'
    | '/auth/callback'
    | '/docs/$'
    | '/events/$id'
    | '/flights/$callsign'
    | '/navdata/preferred-routes'
    | '/users/me'
    | '/controllers/'
    | '/events/'
    | '/flights/'
    | '/users/'
    | '/_doc/airspace/fir'
    | '/_doc/airspace/rvsm'
    | '/_doc/airspace/sop'
    | '/_doc/airspace/station'
    | '/_doc/airspace/vfr'
    | '/_doc/controller/become-a-controller'
    | '/_doc/controller/controller-list'
    | '/_doc/controller/controller-regulations'
    | '/_doc/controller/loa'
    | '/_doc/controller/sector'
    | '/_doc/controller/visiting-and-transferring'
    | '/_doc/division/api'
    | '/_doc/division/introduction'
    | '/_doc/division/meeting'
    | '/_doc/division/privacy'
    | '/_doc/division/staff'
    | '/_doc/pilot/introduction-to-fly'
    | '/_doc/pilot/pilot-softwares'
    | '/_doc/pilot/start-to-fly'
    | '/_doc/pilot/ts3'
    | '/controllers/applications/$id'
    | '/controllers/applications/new'
    | '/controllers/trainings/$id'
    | '/docs/utils/image'
    | '/controllers/applications/'
    | '/controllers/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  FlightsRoute: typeof FlightsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DocsSplatRoute: typeof DocsSplatRoute
  NavdataPreferredRoutesRoute: typeof NavdataPreferredRoutesRoute
  UsersMeRoute: typeof UsersMeRoute
  ControllersIndexRoute: typeof ControllersIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  DocAirspaceFirRoute: typeof DocAirspaceFirRoute
  DocAirspaceRvsmRoute: typeof DocAirspaceRvsmRoute
  DocAirspaceSopRoute: typeof DocAirspaceSopRoute
  DocAirspaceStationRoute: typeof DocAirspaceStationRoute
  DocAirspaceVfrRoute: typeof DocAirspaceVfrRoute
  DocControllerBecomeAControllerRoute: typeof DocControllerBecomeAControllerRoute
  DocControllerControllerListRoute: typeof DocControllerControllerListRoute
  DocControllerControllerRegulationsRoute: typeof DocControllerControllerRegulationsRoute
  DocControllerLoaRoute: typeof DocControllerLoaRoute
  DocControllerSectorRoute: typeof DocControllerSectorRoute
  DocControllerVisitingAndTransferringRoute: typeof DocControllerVisitingAndTransferringRoute
  DocDivisionApiRoute: typeof DocDivisionApiRoute
  DocDivisionIntroductionRoute: typeof DocDivisionIntroductionRoute
  DocDivisionMeetingRoute: typeof DocDivisionMeetingRoute
  DocDivisionPrivacyRoute: typeof DocDivisionPrivacyRoute
  DocDivisionStaffRoute: typeof DocDivisionStaffRoute
  DocPilotIntroductionToFlyRoute: typeof DocPilotIntroductionToFlyRoute
  DocPilotPilotSoftwaresRoute: typeof DocPilotPilotSoftwaresRoute
  DocPilotStartToFlyRoute: typeof DocPilotStartToFlyRoute
  DocPilotTs3Route: typeof DocPilotTs3Route
  ControllersApplicationsIdRoute: typeof ControllersApplicationsIdRoute
  ControllersApplicationsNewRoute: typeof ControllersApplicationsNewRoute
  ControllersTrainingsIdRoute: typeof ControllersTrainingsIdRoute
  DocsUtilsImageRoute: typeof DocsUtilsImageRoute
  ControllersApplicationsIndexRoute: typeof ControllersApplicationsIndexRoute
  ControllersTrainingsIndexRoute: typeof ControllersTrainingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/': {
      id: '/flights/'
      path: '/'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof FlightsRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/controllers/': {
      id: '/controllers/'
      path: '/controllers'
      fullPath: '/controllers'
      preLoaderRoute: typeof ControllersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me': {
      id: '/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navdata/preferred-routes': {
      id: '/navdata/preferred-routes'
      path: '/navdata/preferred-routes'
      fullPath: '/navdata/preferred-routes'
      preLoaderRoute: typeof NavdataPreferredRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$callsign': {
      id: '/flights/$callsign'
      path: '/$callsign'
      fullPath: '/flights/$callsign'
      preLoaderRoute: typeof FlightsCallsignRouteImport
      parentRoute: typeof FlightsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/trainings/': {
      id: '/controllers/trainings/'
      path: '/controllers/trainings'
      fullPath: '/controllers/trainings'
      preLoaderRoute: typeof ControllersTrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/applications/': {
      id: '/controllers/applications/'
      path: '/controllers/applications'
      fullPath: '/controllers/applications'
      preLoaderRoute: typeof ControllersApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/utils/image': {
      id: '/docs/utils/image'
      path: '/docs/utils/image'
      fullPath: '/docs/utils/image'
      preLoaderRoute: typeof DocsUtilsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/trainings/$id': {
      id: '/controllers/trainings/$id'
      path: '/controllers/trainings/$id'
      fullPath: '/controllers/trainings/$id'
      preLoaderRoute: typeof ControllersTrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/applications/new': {
      id: '/controllers/applications/new'
      path: '/controllers/applications/new'
      fullPath: '/controllers/applications/new'
      preLoaderRoute: typeof ControllersApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/applications/$id': {
      id: '/controllers/applications/$id'
      path: '/controllers/applications/$id'
      fullPath: '/controllers/applications/$id'
      preLoaderRoute: typeof ControllersApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/pilot/ts3': {
      id: '/_doc/pilot/ts3'
      path: '/pilot/ts3'
      fullPath: '/pilot/ts3'
      preLoaderRoute: typeof DocPilotTs3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/pilot/start-to-fly': {
      id: '/_doc/pilot/start-to-fly'
      path: '/pilot/start-to-fly'
      fullPath: '/pilot/start-to-fly'
      preLoaderRoute: typeof DocPilotStartToFlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/pilot/pilot-softwares': {
      id: '/_doc/pilot/pilot-softwares'
      path: '/pilot/pilot-softwares'
      fullPath: '/pilot/pilot-softwares'
      preLoaderRoute: typeof DocPilotPilotSoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/pilot/introduction-to-fly': {
      id: '/_doc/pilot/introduction-to-fly'
      path: '/pilot/introduction-to-fly'
      fullPath: '/pilot/introduction-to-fly'
      preLoaderRoute: typeof DocPilotIntroductionToFlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/division/staff': {
      id: '/_doc/division/staff'
      path: '/division/staff'
      fullPath: '/division/staff'
      preLoaderRoute: typeof DocDivisionStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/division/privacy': {
      id: '/_doc/division/privacy'
      path: '/division/privacy'
      fullPath: '/division/privacy'
      preLoaderRoute: typeof DocDivisionPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/division/meeting': {
      id: '/_doc/division/meeting'
      path: '/division/meeting'
      fullPath: '/division/meeting'
      preLoaderRoute: typeof DocDivisionMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/division/introduction': {
      id: '/_doc/division/introduction'
      path: '/division/introduction'
      fullPath: '/division/introduction'
      preLoaderRoute: typeof DocDivisionIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/division/api': {
      id: '/_doc/division/api'
      path: '/division/api'
      fullPath: '/division/api'
      preLoaderRoute: typeof DocDivisionApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/visiting-and-transferring': {
      id: '/_doc/controller/visiting-and-transferring'
      path: '/controller/visiting-and-transferring'
      fullPath: '/controller/visiting-and-transferring'
      preLoaderRoute: typeof DocControllerVisitingAndTransferringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/sector': {
      id: '/_doc/controller/sector'
      path: '/controller/sector'
      fullPath: '/controller/sector'
      preLoaderRoute: typeof DocControllerSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/loa': {
      id: '/_doc/controller/loa'
      path: '/controller/loa'
      fullPath: '/controller/loa'
      preLoaderRoute: typeof DocControllerLoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/controller-regulations': {
      id: '/_doc/controller/controller-regulations'
      path: '/controller/controller-regulations'
      fullPath: '/controller/controller-regulations'
      preLoaderRoute: typeof DocControllerControllerRegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/controller-list': {
      id: '/_doc/controller/controller-list'
      path: '/controller/controller-list'
      fullPath: '/controller/controller-list'
      preLoaderRoute: typeof DocControllerControllerListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/controller/become-a-controller': {
      id: '/_doc/controller/become-a-controller'
      path: '/controller/become-a-controller'
      fullPath: '/controller/become-a-controller'
      preLoaderRoute: typeof DocControllerBecomeAControllerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/airspace/vfr': {
      id: '/_doc/airspace/vfr'
      path: '/airspace/vfr'
      fullPath: '/airspace/vfr'
      preLoaderRoute: typeof DocAirspaceVfrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/airspace/station': {
      id: '/_doc/airspace/station'
      path: '/airspace/station'
      fullPath: '/airspace/station'
      preLoaderRoute: typeof DocAirspaceStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/airspace/sop': {
      id: '/_doc/airspace/sop'
      path: '/airspace/sop'
      fullPath: '/airspace/sop'
      preLoaderRoute: typeof DocAirspaceSopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/airspace/rvsm': {
      id: '/_doc/airspace/rvsm'
      path: '/airspace/rvsm'
      fullPath: '/airspace/rvsm'
      preLoaderRoute: typeof DocAirspaceRvsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doc/airspace/fir': {
      id: '/_doc/airspace/fir'
      path: '/airspace/fir'
      fullPath: '/airspace/fir'
      preLoaderRoute: typeof DocAirspaceFirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface FlightsRouteChildren {
  FlightsCallsignRoute: typeof FlightsCallsignRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
}

const FlightsRouteChildren: FlightsRouteChildren = {
  FlightsCallsignRoute: FlightsCallsignRoute,
  FlightsIndexRoute: FlightsIndexRoute,
}

const FlightsRouteWithChildren =
  FlightsRoute._addFileChildren(FlightsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  FlightsRoute: FlightsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DocsSplatRoute: DocsSplatRoute,
  NavdataPreferredRoutesRoute: NavdataPreferredRoutesRoute,
  UsersMeRoute: UsersMeRoute,
  ControllersIndexRoute: ControllersIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  DocAirspaceFirRoute: DocAirspaceFirRoute,
  DocAirspaceRvsmRoute: DocAirspaceRvsmRoute,
  DocAirspaceSopRoute: DocAirspaceSopRoute,
  DocAirspaceStationRoute: DocAirspaceStationRoute,
  DocAirspaceVfrRoute: DocAirspaceVfrRoute,
  DocControllerBecomeAControllerRoute: DocControllerBecomeAControllerRoute,
  DocControllerControllerListRoute: DocControllerControllerListRoute,
  DocControllerControllerRegulationsRoute:
    DocControllerControllerRegulationsRoute,
  DocControllerLoaRoute: DocControllerLoaRoute,
  DocControllerSectorRoute: DocControllerSectorRoute,
  DocControllerVisitingAndTransferringRoute:
    DocControllerVisitingAndTransferringRoute,
  DocDivisionApiRoute: DocDivisionApiRoute,
  DocDivisionIntroductionRoute: DocDivisionIntroductionRoute,
  DocDivisionMeetingRoute: DocDivisionMeetingRoute,
  DocDivisionPrivacyRoute: DocDivisionPrivacyRoute,
  DocDivisionStaffRoute: DocDivisionStaffRoute,
  DocPilotIntroductionToFlyRoute: DocPilotIntroductionToFlyRoute,
  DocPilotPilotSoftwaresRoute: DocPilotPilotSoftwaresRoute,
  DocPilotStartToFlyRoute: DocPilotStartToFlyRoute,
  DocPilotTs3Route: DocPilotTs3Route,
  ControllersApplicationsIdRoute: ControllersApplicationsIdRoute,
  ControllersApplicationsNewRoute: ControllersApplicationsNewRoute,
  ControllersTrainingsIdRoute: ControllersTrainingsIdRoute,
  DocsUtilsImageRoute: DocsUtilsImageRoute,
  ControllersApplicationsIndexRoute: ControllersApplicationsIndexRoute,
  ControllersTrainingsIndexRoute: ControllersTrainingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
